### ISSUE TITLE
Pulled out items/stacks vanishing when inventory is full

### ISSUE THREAD

**Issue by gentlewatcher** [notjoe7F/stockpile#11]
**Describe the bug**
The act of pulling out items from a barrel does not care if you have room in your inventory and will remove items from the value of the barrel and not spawn the items onto the ground, thus they vanish.

**To Reproduce**
1. Place a 'barrel' 
2. Right-click on the 'barrel to add to its "inventory"'(unless its a barrel with nbt/items already in it then skip this step)
3.Put anything (that is not the item in the barrel you placed) and fill your inventory, does not have to be full stacks, just have at least something in every slot.
4.Now left click the barrel to "take an item out" and the value of the barrel will go down, but with no inventory slots free the "item" "vanishes"

**Expected behavior**
When on step 4 listed above the item should be put on the ground thus it stays in the world and is not just deleted, just like how a chest in principle works and how the better barrels mod from previous versions worked.

OR make it so if inventory is "full"(no valid slots for the item to go into, including those that are the same as the item but not at stack limit) then make the item stay in the barrel (you could also add in just one function for if there is no change in inventory ie: if the item did not go into the inventory, then put the item back in the barrel

**Screenshots**
![javaw_2018-08-31_22-35-59](https://user-images.githubusercontent.com/34151191/44942463-a0c3e280-ad6e-11e8-8b37-34d706ac837f.png)
![javaw_2018-08-31_22-36-30](https://user-images.githubusercontent.com/34151191/44942462-a0c3e280-ad6e-11e8-8cb0-79b0a3189566.png)

**Environment:**
 - Rift Version [i.e. 1.0.3-45]
 - Stockpile Version [i.e. 0.1.1]

**Comment by notjoe7F** [comment]
Thanks for submitting an issue. This has been fixed as of Stockpile 0.3.0 (#4). If it persists after upgrading (or there is a specific reason to stay on the older version), feel free to continue this thread.
