### ISSUE TITLE
Game crash with most recent update (0.3.0)

### ISSUE THREAD

**Issue by Manjack4060** [notjoe7F/stockpile#12]
Same as title, game crashes to launcher when trying to launch the game with the newest version of rift that stockpile supposedly supports. Works fine with stockpile 0.2.0.

**To Reproduce**
Steps to reproduce the behaviour:
Install rift
Install Stockpile
Launch game

**Expected behaviour**
Game should launch as per

**Screenshots**
https://gyazo.com/67fde2ae13e361b8b34f8a13fa01721b

**Environment:**
 - Rift Version [1.13-rift-1.0.4-66]
 - Stockpile Version [0.3.0]

**Additional context**
Same occurred with only rift and stockpile installed

**Comment by notjoe7F** [comment]
Sorry for the late response-- I haven't particularly had time to work on modding! As of version 0.3.0, Stockpile depends on Riftlin. Try installing that as well, and see if the problem persists.

**Comment by notjoe7F** [comment]
The Rift version of Stockpile has been retired in favor of 0.4 and later on Fabric. As such, this issue will be closed-- but, if the issue persists on 0.4 or later, please post about it!
