### ISSUE TITLE
One of ten barrels cannot be broken nor filled

### ISSUE THREAD

**Issue by Knito58** [notjoe7F/stockpile#2]
Somehow one of that barrels is desynced. The breaking animation is shown and when the barrel breaks it is placed back immediately - it is undestructable. It is empty and has a clear monitor.
The latest.log has some complaints about a Trashcan which stands nearby.
https://pastebin.com/3vFsJe4C

**Comment by notjoe7F** [comment]
Thanks for posting your issue. I haven't been able to reproduce this so far after placing and breaking barrels and trash cans in both a dev environment and with the CF release-- what versions of Stockpile and Rift are you using? Can specific steps be used to reproduce the desynced behavior?

**Comment by Knito58** [comment]
I'm using Rift 1.0.3-45 and Stockpile 0.1.1. Sorry for missing this piece of info. I simply stacked a wall of all barrels I could afford and when I wanted to put sand into said barrel it wouldn't work. When trying to replace it that action fails. All the other barrels are fine. 

First I tried to put something into the trash bin and went opening and closing the lid. Then I broke it and placed it back. Then the wall of barrels around it. I believe the indestructable barrel is purely random. I even successfully broke a dirt barrel and used some chests in an anvil on it. After replacing it there was a lot of free space in that barrel. Everything else seems to work as expected. There's no obvious reason why that barrel resists. I didn't do anything special with it. The first try to use it after placing it failed.

**Comment by notjoe7F** [comment]
I was able to reproduce this and (hopefully) solve the issue-- it looks like the trash can wasn't properly cleaning up its tile entity after being broken. A new version should be pushed within a day or so.

**Comment by notjoe7F** [comment]
It looks like future instances of the issue have been fixed, but not existing ones. Try setting the offending block to air with `/setblock` and see if that allows you to place a new one that functions properly. If cheats are off in your world, you can enable them temporarily by opening it to LAN.

**Comment by Knito58** [comment]
Ok. Cheats are off. Will try this LAN thing when I get back to 1.13.

**Comment by Knito58** [comment]
/setblock -61 67 -115 minecraft:air replace

"An unexpected error occurred trying to execute that command"

Now /setblock -61 67 -115 minecraft:air destroy

did the job. First the barrel was still there, after moving around and clicking it, it was gone. Yay! Silly me then replaced that empty room with a barrel which suddenly was in the hotbar and the error was there again. Seems I put that old barrel back. After some more trying now there's a barrel in place containing sand. I now seem to have 4 barrels which, when in that place, do not work. Will throw them into lave by time.

Thanks for the hint.

**Comment by notjoe7F** [comment]
No problem. I'll see if I can add some further verification in the future to prevent residual issues from past versions like this. If that spot continues to make trouble with new barrels, feel free to open another issue if you're up to it-- there might be a different problem at hand.

**Comment by Knito58** [comment]
Thank you. Don't do too much for the "oldies". Great mod!
