### ISSUE TITLE
Barrel Drops itself in creative

### ISSUE THREAD

**Issue by jkenyonc** [notjoe7F/stockpile#5]
the barrels drop as items even when in creative, instead of just disappearing. should be easy to fix.

**Comment by jkenyonc** [comment]
this might be intentional, but there should be a way to avoid it

**Comment by notjoe7F** [comment]
This was originally intended so that you could keep a barrel's data if you wanted to move it or replace one that's glitched out or something, but I agree that there should be a way to avoid it. I'll see if I can make it so that they only drop for creative players if they're crouching.

**Comment by jkenyonc** [comment]
Maybe you could just make pick block in creative give you the filled barrel?

**Comment by notjoe7F** [comment]
Added for the next version. Barrels can now be copied in creative mode via the pick block functionality.
