### ISSUE TITLE
(Empty) Barrels will not accept hopper input

### ISSUE THREAD

**Issue by Kisonu** [notjoe7F/stockpile#6]
SO i decided i was going to use this mod to expand my 1.13 storage sorting system. Sadly i had to basically rebuild it all as it clogged up due to the barrels not accepting hopper input when empty. I'm not sure if this is intentional or not but would it be possible to allow for the empty barrels to accept hopper input and then only fill with that item?  Maybe provide a GUI to toggle this functionality?

**Comment by notjoe7F** [comment]
This was the intention but I definitely think the option should be available to get the behavior you're after here. I'll add an item locking/unlocking mechanism (similar to TE caches) for the next version.
